spring :
  datasource:
    url: jdbc:mariadb://mysql-orely4.alwaysdata.net/orely4_goldenline_bdd
      password: bpOFG0YcmbeTg0RD
      username: orely4_goldline
      driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

